version: "3"

volumes:
  db-store:
  db-testing-store:

networks:
  nw_tdd:
    driver: bridge

services:

  # app server
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    volumes:
      - ${APP_PATH}:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_TESTING_HOST=${DB_TESTING_HOST}
      - DB_TESTING_DATABASE=${DB_TESTING_DATABASE}
      - DB_TESTING_USERNAME=${DB_TESTING_USERNAME}
      - DB_TESTING_PASSWORD=${DB_TESTING_PASSWORD}
      - TZ=${TZ}
    networks:
      - nw_tdd

  # web server
  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${APP_PATH}:/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
    networks:
      - nw_tdd

  # Database Server
  db:
    image: mysql:8.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/log:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    networks:
      - nw_tdd

  # Database Server for Test
  db-test:
    image: mysql:8.0
    volumes:
      - db-testing-store:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_TESTING_DATABASE}
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=${DB_TESTING_USERNAME}
      - MYSQL_PASSWORD=${DB_TESTING_PASSWORD}
      - TZ=${TZ}
    networks:
      - nw_tdd

  # Database WebGUI
  adminer:
    image: adminer:latest
    ports:
      - 8080:8080
    networks:
      - nw_tdd

